name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push HTTPD image
        uses: docker/build-push-action@v4
        with:
          context: ./httpd
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/httpd:latest

      - name: Build and push Business Logic image
        uses: docker/build-push-action@v4
        with:
          context: ./business-logic
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/business-logic:latest

      - name: Run tests
        run: |
          docker-compose up -d
          docker-compose exec business_logic python -m pytest tests/
          docker-compose down

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to production
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/httpd:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/business-logic:latest
            docker-compose -f /path/to/docker-compose.yml up -d
          "
